# docker-compose.yml
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      # Uncomment below to specify versions
      # args:
      #   PYTHON_VERSION:
      #   POETRY_VERSION:
      target: development
    image: {{cookiecutter.project_name}}-web:dev
    # This overrides the CMD in the Dockerfile
    command:
      - "sh"
      - "-c"
      - |
        poetry add debugpy &&
        poetry run python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
      - 5678:5678
